name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * *"

permissions: write-all

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
